name: flutter_sandbox_web
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  pdf: ^3.10.1
  printing: ^5.10.3
  csv: ^5.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/card.png
